spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.smart.shop.personal.details.domain.entity
server:
  port: 8091